"""Supermodel magazine editorial roster v1.3."""

from __future__ import annotations

SUPERMODEL_ROSTER_10: list[dict[str, str | int]] = [
    {"name": "Valentina Rossi", "age": 25, "ethnicity": "Italian", "visuals": "striking supermodel beauty with sharp defined cheekbones, captivating dark eyes, flawless porcelain skin, perfect symmetrical features, magnetic presence", "outfit": "asymmetric sculptural black wool coat with metallic petal accents and exaggerated shoulders"},
    {"name": "Zara Khan", "age": 26, "ethnicity": "Indian-British", "visuals": "stunning ethereal beauty with long flowing dark hair, delicate yet powerful features, warm glowing golden skin, intense expressive eyes, flawless proportions", "outfit": "flowing emerald silk gown with dramatic cape sleeves and crystal embellishments"},
    {"name": "Liora Voss", "age": 24, "ethnicity": "Dutch-German", "visuals": "very attractive willowy supermodel with platinum blonde blunt bob, striking blue eyes, pale flawless porcelain skin, high cheekbones, captivating symmetry", "outfit": "deconstructed white architectural dress with geometric cut-outs and structured pleats"},
    {"name": "Sofia Alvarez", "age": 27, "ethnicity": "Brazilian", "visuals": "stunning curvy athletic supermodel with warm tan skin, voluminous curly dark hair, radiant smile, flawless glowing complexion, powerful magnetic presence", "outfit": "vibrant red metallic draped gown with high slit and bold shoulder details"},
    {"name": "Anya Petrova", "age": 23, "ethnicity": "Russian", "visuals": "striking ice-blonde supermodel with sleek ponytail, cool flawless porcelain skin, sharp jawline, intense captivating eyes, perfect bone structure", "outfit": "futuristic silver chrome jacket over sheer black gown with dramatic train"},
    {"name": "Nadia Okoro", "age": 28, "ethnicity": "Nigerian-French", "visuals": "radiant dark-skinned supermodel with intricate braids and gold threads, high cheekbones, flawless glowing skin, powerful striking presence, perfect symmetry", "outfit": "bold gold and saffron African-inspired avant-garde wrap dress with sculptural sleeves"},
    {"name": "Freya Lind", "age": 22, "ethnicity": "Swedish", "visuals": "stunning freckled fair-skinned supermodel with strawberry-blonde waves, soft yet commanding features, flawless skin, captivating gentle eyes", "outfit": "soft pastel oversized knit coat over minimalist slip dress with pearl accents"},
    {"name": "Mei Lin Chen", "age": 25, "ethnicity": "Taiwanese", "visuals": "delicate yet stunning supermodel with straight black hair and blunt bangs, flawless porcelain skin, elegant neckline, intense captivating eyes", "outfit": "crimson silk cheongsam reimagined as avant-garde asymmetrical gown with modern cut-outs"},
    {"name": "Isolde Moreau", "age": 26, "ethnicity": "French", "visuals": "androgynous stunning elegance with short dark pixie cut, smoky intense eyes, pale flawless skin, sharp magnetic features", "outfit": "tailored black tuxedo gown with dramatic cape and crystal buttons"},
    {"name": "Priya Singh", "age": 24, "ethnicity": "Indian-Canadian", "visuals": "warm golden stunning supermodel with long wavy hair and subtle highlights, expressive captivating eyes, flawless glowing skin, perfect proportions", "outfit": "jewel-toned sari-inspired draped gown in sapphire with modern metallic embroidery"},
]

SUPERMODEL_NAMES: list[str] = [m["name"] for m in SUPERMODEL_ROSTER_10]