"""Fifty unique fictional actors — 25 women, 25 men — sorted by gender and world region."""

from __future__ import annotations

from actor_profile_generator import ActorProfile

_COMFORT_F = (
    "Story-serving intimacy per Protocol v1.3; clinical prompt language; "
    "PG-13 baseline unless canon escalates with compliance review."
)
_COMFORT_M = (
    "Story-serving intimacy per Protocol v1.3; clinical prompt language; "
    "PG-13 baseline; no explicit content."
)
_TATTOO_NONE = "None — continuity: no tattoo additions without canon update."


def _a(
    *,
    stage_name: str,
    gender: str,
    world_region: str,
    age: int,
    ethnicity: str,
    nationality: str,
    heritage: str,
    languages: list[str],
    physical: str,
    archetypes: list[str],
    moods: list[str],
    on_screen_mood: str,
    off_screen_mood: str,
    performance_style: str,
    voice_notes: str,
    personality: str,
    signature_looks: str,
    casting_notes: str,
    full_legal_name: str | None = None,
    refs: list[str] | None = None,
    tattoos: str = _TATTOO_NONE,
    wardrobe_color: str = "black",
    dob: str = "Month DD, YYYY",
) -> ActorProfile:
    return ActorProfile(
        stage_name=stage_name,
        full_legal_name=full_legal_name or stage_name,
        professional_stage_name=stage_name,
        age=age,
        date_of_birth=dob,
        ethnicity=ethnicity,
        nationality=nationality,
        heritage=heritage,
        languages=languages,
        base_physical_description=physical,
        archetypes=archetypes,
        performance_style=performance_style,
        voice_notes=voice_notes,
        on_screen_comfort=_COMFORT_F if gender == "female" else _COMFORT_M,
        personality=personality,
        base_reference_images=refs
        or [
            f"Neutral casting wardrobe anchor — {stage_name}",
            f"Primary story wardrobe — {stage_name}",
        ],
        tattoo_inventory=tattoos,
        signature_looks=signature_looks,
        casting_notes=casting_notes,
        gender=gender,
        world_region=world_region,
        mood_modifiers=moods,
        on_screen_mood=on_screen_mood,
        off_screen_mood=off_screen_mood,
        casting_wardrobe_color=wardrobe_color,
    )


ROSTER_50: list[ActorProfile] = [
    # ── WOMEN (25) ──────────────────────────────────────────────────────────
    _a(
        stage_name="Elinor Trevelyan",
        gender="female",
        world_region="europe_west",
        age=26,
        ethnicity="White British",
        nationality="United Kingdom",
        heritage="Cornish — Penwith coast (St Ives / Zennor)",
        languages=["English (RP with West Country lilt)", "Cornish (basic phrases)"],
        physical=(
            "5'7\", lean swimmer's build, honey-blonde wavy hair to mid-back, grey-green eyes, "
            "fair freckled skin, gold stud earrings."
        ),
        archetypes=["Coastal drama lead", "Period ingénue with steel", "Grief-carrier"],
        moods=["reserved", "wry", "steadfast"],
        on_screen_mood="Stillness first; warmth leaks through micro-smiles and delayed answers.",
        off_screen_mood="Dry Cornish humor in interviews; gentle with crew; stubborn about blocking.",
        performance_style="Underplayed British naturalism; emotional turns in the exhale.",
        voice_notes="West Country warmth when relaxed; crisp RP under pressure.",
        personality="Practical, tide-checking composure; fierce loyalty beneath reserve.",
        signature_looks="Wind-tousled blonde, minimal makeup, slate-and-cream wardrobe.",
        casting_notes="Lead/co-lead British drama; environment as co-character.",
        dob="August 2, 1999",
        full_legal_name="Elinor Catherine Trevelyan",
    ),
    _a(
        stage_name="Valentina Moreau",
        gender="female",
        world_region="europe_west",
        age=47,
        ethnicity="French-Algerian",
        nationality="United States",
        heritage="Algiers maternal line; Marseille paternal roots",
        languages=["French (native)", "English (fluent)", "Arabic (conversational)"],
        physical=(
            "5'8\", elegant hourglass build, shoulder-length wavy chestnut hair with silver strands, "
            "almond hazel-green eyes, warm olive skin."
        ),
        archetypes=["Mature femme lead", "Power broker with grace", "Mother-figure with secrets"],
        moods=["charming", "commanding", "knowing"],
        on_screen_mood="Charming surface; commanding stillness when challenged.",
        off_screen_mood="Effortlessly gracious on set; witty, slightly teasing with trusted collaborators.",
        performance_style="Precision and poise; every gesture placed.",
        voice_notes="Low melodic register; French cadence on emotional peaks.",
        personality="Reads rooms instantly; warmth is selective, never performed.",
        signature_looks="Deep wine and emerald tones, silk, understated gold jewelry.",
        casting_notes="Authority roles; age must lead every prompt.",
        wardrobe_color="deep wine red",
        dob="November 3, 1978",
        full_legal_name="Valentina Amira Moreau",
    ),
    _a(
        stage_name="Sofia Andersson",
        gender="female",
        world_region="europe_west",
        age=29,
        ethnicity="Swedish",
        nationality="Sweden",
        heritage="Stockholm urban; Lapland summer family cabin line",
        languages=["Swedish (native)", "English (fluent neutral)"],
        physical=(
            "5'10\", long-limbed athletic build, straight platinum-blonde bob, ice-blue eyes, "
            "fair Nordic skin, minimal brows."
        ),
        archetypes=["Cool investigator", "Nordic noir lead", "Quiet avenger"],
        moods=["observant", "cool", "deadpan"],
        on_screen_mood="Minimal expression; impact lands in stillness and eye-line.",
        off_screen_mood="Deadpan humor off-camera; surprisingly playful in downtime.",
        performance_style="Economy of motion; less-is-more Nordic restraint.",
        voice_notes="Clear, cool timbre; softens one notch in intimacy.",
        personality="Observer first; loyalty earned slowly, kept fiercely.",
        signature_looks="Monochrome layers, clean lines, no-logo minimalism.",
        casting_notes="Noir and thriller; stillness is the weapon.",
        wardrobe_color="navy",
        dob="January 19, 1997",
    ),
    _a(
        stage_name="Chiara Romano",
        gender="female",
        world_region="europe_west",
        age=34,
        ethnicity="Italian",
        nationality="Italy",
        heritage="Rome and Naples family roots",
        languages=["Italian (native)", "English (fluent)", "French (conversational)"],
        physical=(
            "5'5\", curvy compact build, thick dark chestnut hair in loose waves, "
            "amber-brown eyes, olive Mediterranean skin, expressive hands."
        ),
        archetypes=["Romantic lead", "Passionate antagonist", "Family saga anchor"],
        moods=["witty", "passionate", "volatile"],
        on_screen_mood="Quick wit under fire; passion reads as conviction not melodrama.",
        off_screen_mood="Animated storyteller; hugs crew; sassy with press.",
        performance_style="High emotional bandwidth with grounded feet.",
        voice_notes="Rich mezzo; laughter arrives before anger.",
        personality="Big heart, fast mouth; protects family above all.",
        signature_looks="Crimson lip, gold hoops, tailored linen and leather.",
        casting_notes="Drama and romance; hands are continuity detail.",
        wardrobe_color="terracotta",
        dob="April 8, 1992",
    ),
    _a(
        stage_name="Emma Larsen",
        gender="female",
        world_region="europe_west",
        age=31,
        ethnicity="Norwegian",
        nationality="Norway",
        heritage="Bergen coastal fishing family",
        languages=["Norwegian (native)", "English (fluent)"],
        physical=(
            "5'9\", strong swimmer's shoulders, strawberry-blonde braid, grey-blue eyes, "
            "light freckles, weather-ready fair skin."
        ),
        archetypes=["Survival drama lead", "Rescue-worker type", "Quiet resilience"],
        moods=["wry", "steady", "blunt"],
        on_screen_mood="Blunt honesty; humor as coping mechanism in crisis.",
        off_screen_mood="Straight-talking, kind; uncomfortable with Hollywood polish.",
        performance_style="Physical truth; exhaustion reads real.",
        voice_notes="Direct cadence; laughs through nose.",
        personality="Fixes problems before discussing feelings.",
        signature_looks="Waxed jacket, wool layers, practical boots.",
        casting_notes="Action and coastal survival; wet-hair continuity common.",
        wardrobe_color="slate grey",
        dob="June 22, 1994",
    ),
    _a(
        stage_name="Maeve O'Sullivan",
        gender="female",
        world_region="europe_west",
        age=28,
        ethnicity="Irish",
        nationality="Ireland",
        heritage="Cork and Kerry roots",
        languages=["English (Irish lilt)", "Irish Gaelic (conversational)"],
        physical=(
            "5'6\", soft athletic build, copper-red curls to shoulders, green-hazel eyes, "
            "fair skin with scattered freckles."
        ),
        archetypes=["Folk-horror lead", "Whimsical best friend", "Truth-teller"],
        moods=["whimsical", "blunt", "warm"],
        on_screen_mood="Whimsy masks steel; blunt lines disarm opponents.",
        off_screen_mood="Sings on set; charming, slightly chaotic energy.",
        performance_style="Musical rhythm to speech; big eyes, small gestures.",
        voice_notes="Lilt thickens when emotional or lying.",
        personality="Story-collector; disarms with humor then lands truth.",
        signature_looks="Aran knit, moss greens, bare-faced freckles.",
        casting_notes="Horror, drama, comedy-drama; hair color locked.",
        wardrobe_color="forest green",
        dob="October 31, 1997",
    ),
    _a(
        stage_name="Anastasia Volkov",
        gender="female",
        world_region="europe_east",
        age=33,
        ethnicity="Russian-American",
        nationality="United States",
        heritage="St. Petersburg lineage; immigrated childhood",
        languages=["Russian (native)", "English (fluent, slight accent)"],
        physical=(
            "5'8\", ballet-trained posture, straight dark auburn hair in low chignon, "
            "pale grey eyes, porcelain skin, sharp cheekbones."
        ),
        archetypes=["Ice-queen lead", "Spy adjacent", "Tragic elegance"],
        moods=["icy", "layered", "precise"],
        on_screen_mood="Controlled frost; one crack per scene maximum.",
        off_screen_mood="Private, cerebral; dry Russian humor with friends.",
        performance_style="Discipline and line; stillness as threat.",
        voice_notes="Low cool register; Russian accent surfaces under stress.",
        personality="Disciplined exterior; romantic only in private canon.",
        signature_looks="Charcoal tailoring, red lip as sole color.",
        casting_notes="Thriller, period, ballet background informs movement.",
        wardrobe_color="charcoal",
        dob="February 14, 1993",
    ),
    _a(
        stage_name="Rachel Cohen",
        gender="female",
        world_region="north_america",
        age=36,
        ethnicity="Jewish-American",
        nationality="United States",
        heritage="Ashkenazi — New York and Philadelphia roots",
        languages=["English (native)", "Hebrew (conversational)"],
        physical=(
            "5'5\", curvy hourglass build, voluminous dark wavy hair, large dark brown eyes, "
            "warm olive skin, prominent cheekbones."
        ),
        archetypes=["Legal drama lead", "Sharp best friend", "Moral center"],
        moods=["sardonic", "sharp", "warm"],
        on_screen_mood="Sardonic armor; warmth for allies only.",
        off_screen_mood="Fast-talking, opinionated, fiercely supportive of cast.",
        performance_style="Timing-driven; punchlines as character.",
        voice_notes="Brooklyn-leaning cadence when passionate.",
        personality="Justice-first; humor deflects vulnerability.",
        signature_looks="Bold lip, structured blazers, statement earrings.",
        casting_notes="Legal, comedy-drama, ensemble anchor.",
        wardrobe_color="emerald green",
        dob="September 9, 1989",
    ),
    _a(
        stage_name="Hana Park",
        gender="female",
        world_region="north_america",
        age=24,
        ethnicity="Korean-American",
        nationality="United States",
        heritage="Seoul and Busan family roots",
        languages=["Korean (fluent)", "English (native West Coast)"],
        physical=(
            "5'4\", petite athletic build, straight jet-black hair with blunt bangs, "
            "dark brown eyes, smooth light olive skin."
        ),
        archetypes=["K-drama energy lead", "Competitive rival", "Hidden softness"],
        moods=["polished", "sassy", "competitive"],
        on_screen_mood="Polished surface; sassy when cornered.",
        off_screen_mood="Type-A on set; surprisingly goofy in video bloopers.",
        performance_style="Clean beats; micro-pout before emotional turn.",
        voice_notes="Bright upper register; Korean code-switch in family scenes.",
        personality="Perfectionist; softness reserved for earned trust.",
        signature_looks="Glossy hair, soft glam, pastel streetwear off-duty.",
        casting_notes="Rom-com, drama, rival roles; bangs continuity.",
        wardrobe_color="coral",
        dob="May 5, 2002",
    ),
    _a(
        stage_name="Bridget Walsh",
        gender="female",
        world_region="north_america",
        age=39,
        ethnicity="Irish-American",
        nationality="United States",
        heritage="Boston Irish Catholic family",
        languages=["English (native, Boston inflection)"],
        physical=(
            "5'7\", sturdy athletic build, chestnut ponytail, blue-grey eyes, "
            "fair skin, faint scar on left eyebrow."
        ),
        archetypes=["Detective lead", "Working-class hero", "Protector"],
        moods=["gruff", "loyal", "funny"],
        on_screen_mood="Gruff delivery; loyalty in action not words.",
        off_screen_mood="Sports-talk with crew; blunt, generous.",
        performance_style="Physical commitment; tired eyes sell long cases.",
        voice_notes="Boston edge; softens for victims' families.",
        personality="Shows love through doing; uncomfortable with praise.",
        signature_looks="Leather jacket, minimal makeup, coffee-stain realism.",
        casting_notes="Crime procedural; scar is continuity.",
        wardrobe_color="black",
        dob="March 17, 1987",
    ),
    _a(
        stage_name="Aiko Nakamura",
        gender="female",
        world_region="east_asia",
        age=26,
        ethnicity="Japanese-American",
        nationality="United States",
        heritage="Osaka and Yokohama roots",
        languages=["Japanese (native)", "English (fluent)"],
        physical=(
            "5'3\", petite athletic build, straight jet-black bob, almond dark brown eyes, "
            "fair-to-light olive skin."
        ),
        archetypes=["Tech noir lead", "Stoic partner", "Precision fighter"],
        moods=["precise", "reserved", "dry"],
        on_screen_mood="Economical emotion; dry humor as rare gift.",
        off_screen_mood="Quiet on set; precise notes; gentle mentor energy.",
        performance_style="Minimalist; impact in timing.",
        voice_notes="Soft neutral tone; sharpens on technical jargon.",
        personality="Calm under chaos; loyalty shown through competence.",
        signature_looks="Clean lines, navy and white, low ponytail.",
        casting_notes="Sci-fi, thriller; movement training visible.",
        wardrobe_color="navy blue",
        dob="July 7, 1999",
    ),
    _a(
        stage_name="Yuki Tanaka",
        gender="female",
        world_region="east_asia",
        age=22,
        ethnicity="Japanese",
        nationality="Japan",
        heritage="Kyoto traditional arts family",
        languages=["Japanese (native, Kansai dialect)", "English (intermediate)"],
        physical=(
            "5'2\", slim build, black hair in high messy bun, round dark eyes, "
            "porcelain skin, delicate jaw."
        ),
        archetypes=["Coming-of-age lead", "Idol-adjacent ingénue", "Rebel daughter"],
        moods=["playful", "deadpan", "earnest"],
        on_screen_mood="Playful default; deadpan when deflecting.",
        off_screen_mood="Bubbly in behind-the-scenes video; earnest with fans.",
        performance_style="Reactive eyes; physical comedy when script allows.",
        voice_notes="Higher register; Kansai warmth in casual scenes.",
        personality="Polite surface; rebellion in small acts.",
        signature_looks="School-uniform canon, pastel off-duty, minimal lip.",
        casting_notes="Youth drama, rom-com; bun hairstyle common.",
        wardrobe_color="white",
        dob="December 1, 2003",
    ),
    _a(
        stage_name="Mei-Ling Chen",
        gender="female",
        world_region="east_asia",
        age=27,
        ethnicity="Taiwanese",
        nationality="Taiwan",
        heritage="Taipei and Tainan roots",
        languages=["Mandarin (native)", "English (fluent)", "Taiwanese Hokkien (conversational)"],
        physical=(
            "5'5\", slim build, straight black hair past shoulders, bright dark eyes, "
            "warm beige skin, gentle smile lines."
        ),
        archetypes=["Romantic lead", "Startup founder type", "Optimist under pressure"],
        moods=["bright", "earnest", "resilient"],
        on_screen_mood="Earnest optimism; resilience when plan fails.",
        off_screen_mood="Encouraging presence; laughs easily on video.",
        performance_style="Open face; listens actively in two-shots.",
        voice_notes="Clear Mandarin; English bright and quick.",
        personality="Builder mentality; hurt shows then converts to action.",
        signature_looks="Soft neutrals, clean skincare glow, modern casual.",
        casting_notes="Romance, tech drama; smile is character signature.",
        wardrobe_color="soft pink",
        dob="August 18, 1998",
    ),
    _a(
        stage_name="Linh Nguyen",
        gender="female",
        world_region="southeast_asia",
        age=25,
        ethnicity="Vietnamese-American",
        nationality="United States",
        heritage="Saigon and Hue family diaspora",
        languages=["Vietnamese (fluent)", "English (native)"],
        physical=(
            "5'4\", slim dancer's build, long straight black hair, warm brown eyes, "
            "golden-beige skin, small silver necklace."
        ),
        archetypes=["Immigrant story lead", "Dance-driven emotion", "Gentle rebel"],
        moods=["gentle", "mischievous", "sensitive"],
        on_screen_mood="Gentle default; mischievous glint before risk.",
        off_screen_mood="Soft-spoken interviews; playful with dance crew on video.",
        performance_style="Movement-first emotion; hands tell story.",
        voice_notes="Soft melodic tone; Vietnamese lullaby cadence in memory scenes.",
        personality="Sensitivity as strength; mischief aimed at injustice.",
        signature_looks="Flowing fabrics, dance rehearsal layers, bare feet.",
        casting_notes="Family saga, dance sequences; necklace continuity.",
        wardrobe_color="teal",
        dob="April 30, 2001",
    ),
    _a(
        stage_name="Priya Malhotra",
        gender="female",
        world_region="south_asia",
        age=37,
        ethnicity="Indian-American",
        nationality="United States",
        heritage="Delhi and Mumbai family roots",
        languages=["Hindi (fluent)", "English (native)", "Punjabi (conversational)"],
        physical=(
            "5'6\", elegant slim-curvy build, long straight black hair, almond deep brown eyes, "
            "warm medium-brown skin."
        ),
        archetypes=["Professional lead", "Matriarch energy", "Moral negotiator"],
        moods=["witty", "elegant", "firm"],
        on_screen_mood="Wit as scalpel; elegance never drops.",
        off_screen_mood="Warm with crew; witty in panel discussions.",
        performance_style="Authority without volume; still hands.",
        voice_notes="Measured cadence; Hindi warmth in family scenes.",
        personality="Standards high; humor disarms before firm boundary.",
        signature_looks="Jewel-tone sarees and modern tailoring, gold studs.",
        casting_notes="Legal, family drama; hair length locked.",
        wardrobe_color="deep teal",
        dob="January 26, 1988",
    ),
    _a(
        stage_name="Amara Singh",
        gender="female",
        world_region="south_asia",
        age=30,
        ethnicity="British Indian",
        nationality="United Kingdom",
        heritage="Punjab and London roots",
        languages=["English (native, London)", "Punjabi (fluent)", "Hindi (conversational)"],
        physical=(
            "5'7\", athletic build, thick black hair in long braid, amber-brown eyes, "
            "warm brown skin, strong brows."
        ),
        archetypes=["Action co-lead", "Rebel lawyer", "Teasing romantic lead"],
        moods=["confident", "teasing", "fierce"],
        on_screen_mood="Confident tease; fierce when protecting others.",
        off_screen_mood="Banter-heavy on set; empowering in behind-the-scenes clips.",
        performance_style="Physical confidence; smile before strike.",
        voice_notes="London crisp; Punjabi warmth with family.",
        personality="Competitive charm; justice and joy intertwined.",
        signature_looks="Leather and kurta fusion, braid, bold brow.",
        casting_notes="Action-comedy, romance; braid continuity.",
        wardrobe_color="burgundy",
        dob="November 11, 1995",
    ),
    _a(
        stage_name="Zara Adebayo",
        gender="female",
        world_region="sub_saharan_africa",
        age=28,
        ethnicity="Nigerian-American",
        nationality="United States",
        heritage="Lagos Yoruba family",
        languages=["English (native)", "Yoruba (conversational)"],
        physical=(
            "5'8\", athletic curvy build, rich deep brown skin, oval face, voluminous coiled hair, "
            "large expressive dark eyes, full lips."
        ),
        archetypes=["Magnetic lead", "CEO energy", "Romantic powerhouse"],
        moods=["bold", "magnetic", "warm"],
        on_screen_mood="Magnetic entrance; warmth for inner circle.",
        off_screen_mood="High energy on video; encouraging leader on set.",
        performance_style="Presence-first; owns frame without shouting.",
        voice_notes="Rich warm timbre; laughter fills room.",
        personality="Ambitious, generous; vulnerability private.",
        signature_looks="Bold color blocks, gold jewelry, natural hair volume.",
        casting_notes="Lead roles; skin tone and hair locked.",
        wardrobe_color="burgundy",
        dob="June 6, 1997",
    ),
    _a(
        stage_name="Nadia Okoro",
        gender="female",
        world_region="sub_saharan_africa",
        age=42,
        ethnicity="Nigerian-British",
        nationality="United Kingdom",
        heritage="Igbo heritage; London raised",
        languages=["English (native, London)", "Igbo (conversational)"],
        physical=(
            "5'9\", powerful athletic-curvy build, rich deep ebony skin, short cropped natural hair, "
            "large expressive dark eyes, strong jaw."
        ),
        archetypes=["Authority figure", "Political thriller lead", "Unshakeable mentor"],
        moods=["commanding", "dry", "principled"],
        on_screen_mood="Command without shouting; dry wit disarms.",
        off_screen_mood="Direct interviews; principled; dry humor off-camera.",
        performance_style="Stillness as power; eye contact weaponized.",
        voice_notes="Low resonant voice; pauses for effect.",
        personality="Principles non-negotiable; care shown through protection.",
        signature_looks="Sculptural tailoring, cropped hair, minimal jewelry.",
        casting_notes="Political, legal, mentor roles.",
        wardrobe_color="black",
        dob="October 2, 1983",
    ),
    _a(
        stage_name="Grace Okonkwo",
        gender="female",
        world_region="sub_saharan_africa",
        age=23,
        ethnicity="Ghanaian",
        nationality="Ghana",
        heritage="Accra and Kumasi roots",
        languages=["English (fluent)", "Twi (native)"],
        physical=(
            "5'6\", slim strong build, short natural coils, radiant dark brown skin, "
            "wide smile, expressive brows."
        ),
        archetypes=["Rising ingénue", "Activist lead", "Joy under pressure"],
        moods=["radiant", "honest", "spirited"],
        on_screen_mood="Radiant honesty; spirit when fighting odds.",
        off_screen_mood="Authentic, uplifting in video content; honest interviews.",
        performance_style="Open emotional access; smile through tears.",
        voice_notes="Bright clear tone; Twi song cadence in celebration scenes.",
        personality="Hope as discipline; honesty over polish.",
        signature_looks="Bold prints, natural hair, gold ear cuffs.",
        casting_notes="Youth drama, activism plots; smile signature.",
        wardrobe_color="gold",
        dob="July 21, 2002",
    ),
    _a(
        stage_name="Bridget Okafor",
        gender="female",
        world_region="sub_saharan_africa",
        age=35,
        ethnicity="Kenyan-British",
        nationality="United Kingdom",
        heritage="Nairobi and London roots",
        languages=["English (native)", "Swahili (fluent)"],
        physical=(
            "5'10\", long-legged athletic build, deep brown skin, braided updo, "
            "almond dark eyes, high cheekbones."
        ),
        archetypes=["Journalist lead", "Ambitious professional", "Warm rival"],
        moods=["ambitious", "warm", "incisive"],
        on_screen_mood="Incisive questions; warmth in rare private beats.",
        off_screen_mood="Ambitious, polished video presence; warm with documentary crews.",
        performance_style="Intellectual urgency; walks with purpose.",
        voice_notes="Crisp British; Swahili softness in family flashbacks.",
        personality="Curiosity-driven; ambition paired with empathy.",
        signature_looks="Press-badge canon, tailored neutrals, braids.",
        casting_notes="Journalism, corporate drama; height accentuate.",
        wardrobe_color="white",
        dob="February 28, 1991",
    ),
    _a(
        stage_name="Isabella Vargas",
        gender="female",
        world_region="latin_america",
        age=29,
        ethnicity="Mexican-American",
        nationality="United States",
        heritage="Guadalajara and Los Angeles roots",
        languages=["Spanish (native)", "English (fluent)"],
        physical=(
            "5'5\", soft hourglass build, long thick wavy dark brown hair, warm hazel-brown eyes, "
            "golden olive skin."
        ),
        archetypes=["Family drama lead", "Passionate romantic", "Comedic firecracker"],
        moods=["passionate", "fiery", "loyal"],
        on_screen_mood="Passion forward; fire aimed at injustice.",
        off_screen_mood="Hugger; loud joyful video personality; loyal friend energy.",
        performance_style="Heart-on-sleeve with grounded feet.",
        voice_notes="Warm mezzo; Spanish emotion peaks.",
        personality="Family-first; temper quick, forgiveness quicker.",
        signature_looks="Earth tones, gold hoops, glossy waves.",
        casting_notes="Family saga, romance; hair volume locked.",
        wardrobe_color="terracotta",
        dob="December 12, 1996",
    ),
    _a(
        stage_name="Carmen Delgado",
        gender="female",
        world_region="latin_america",
        age=32,
        ethnicity="Colombian",
        nationality="Colombia",
        heritage="Bogotá and Cartagena roots",
        languages=["Spanish (native)", "English (fluent)"],
        physical=(
            "5'6\", curvy athletic build, dark curly hair to shoulders, coffee-brown eyes, "
            "warm caramel skin."
        ),
        archetypes=["Strategic operator", "Dance-club queen", "Survivor lead"],
        moods=["vivacious", "strategic", "defiant"],
        on_screen_mood="Vivacious mask; strategic mind visible in stillness.",
        off_screen_mood="Party energy on video; strategic about career interviews.",
        performance_style="Rhythm in hips and speech; defiance in chin.",
        voice_notes="Smoky alto; laughter low and real.",
        personality="Survivor's optimism; strategy beneath sparkle.",
        signature_looks="Sequins and denim, red lip, curls.",
        casting_notes="Crime, dance, romance; curls continuity.",
        wardrobe_color="red",
        dob="August 8, 1993",
    ),
    _a(
        stage_name="Fatima Al-Hassan",
        gender="female",
        world_region="middle_east_north_africa",
        age=28,
        ethnicity="Moroccan-French",
        nationality="France",
        heritage="Casablanca and Paris roots",
        languages=["French (native)", "Arabic (fluent)", "English (fluent)"],
        physical=(
            "5'7\", slim poised build, dark wavy hair to mid-back, deep brown eyes, "
            "olive-gold skin, arched brows."
        ),
        archetypes=["Fashion-world lead", "Poised outsider", "Quiet rebel"],
        moods=["poised", "fierce", "observant"],
        on_screen_mood="Poise under scrutiny; fierce when cornered.",
        off_screen_mood="Elegant interviews; fierce advocate off-screen in video essays.",
        performance_style="Still posture; eyes carry subtext.",
        voice_notes="French precision; Arabic warmth in family scenes.",
        personality="Dual-world navigation; pride without apology.",
        signature_looks="Structured modest fashion, gold details, sleek hair.",
        casting_notes="Drama, fashion; modesty variants per script.",
        wardrobe_color="black",
        dob="March 3, 1998",
    ),
    _a(
        stage_name="Layla Mansour",
        gender="female",
        world_region="middle_east_north_africa",
        age=31,
        ethnicity="Lebanese-Canadian",
        nationality="Canada",
        heritage="Beirut and Montreal roots",
        languages=["French (fluent)", "Arabic (fluent)", "English (native)"],
        physical=(
            "5'6\", slim build, chestnut hair with auburn highlights, green-brown eyes, "
            "light olive skin, defined nose."
        ),
        archetypes=["War-zone journalist", "Eloquent defender", "Guarded romantic"],
        moods=["eloquent", "guarded", "empathetic"],
        on_screen_mood="Eloquent under fire; guard drops in love scenes only.",
        off_screen_mood="Guarded press; empathetic documentary narration voice.",
        performance_style="Words as weapons and bandages.",
        voice_notes="Trilingual code-switch; Arabic poetry cadence.",
        personality="Empathy costs her; eloquence is survival.",
        signature_looks="Field vest canon, understated makeup, highlights.",
        casting_notes="Journalism, war drama; highlights locked.",
        wardrobe_color="olive",
        dob="September 15, 1994",
    ),
    _a(
        stage_name="Tessa Walsh",
        gender="female",
        world_region="oceania_pacific",
        age=27,
        ethnicity="Australian",
        nationality="Australia",
        heritage="Sydney coastal; rural NSW farm summers",
        languages=["English (native Australian)"],
        physical=(
            "5'8\", sun-weathered athletic build, sandy-blonde sun-streaked hair, blue eyes, "
            "freckled tan skin."
        ),
        archetypes=["Surf drama lead", "Laid-back detective", "Reluctant hero"],
        moods=["laid-back", "charming", "stubborn"],
        on_screen_mood="Laid-back until injustice; charming deflection.",
        off_screen_mood="Surf-town charm in videos; stubborn about safety on set.",
        performance_style="Relaxed body; urgency in eyes.",
        voice_notes="Australian drawl; sharpens in crisis.",
        personality="Avoids conflict until line crossed.",
        signature_looks="Sun-bleached hair, board shorts off-duty, zinc sunscreen.",
        casting_notes="Coastal, crime; tan lines continuity optional.",
        wardrobe_color="cobalt blue",
        dob="January 26, 1999",
    ),
    # ── MEN (25) ────────────────────────────────────────────────────────────
    _a(
        stage_name="James Whitmore",
        gender="male",
        world_region="europe_west",
        age=38,
        ethnicity="White British",
        nationality="United Kingdom",
        heritage="Yorkshire and London roots",
        languages=["English (native RP with Yorkshire undertones)"],
        physical=(
            "6'1\", broad-shouldered lean build, short dark brown hair, grey-blue eyes, "
            "fair skin, light stubble default."
        ),
        archetypes=["Stoic lead", "Military officer", "Dry mentor"],
        moods=["stoic", "dry", "dependable"],
        on_screen_mood="Stoic default; dry humor one line per scene.",
        off_screen_mood="Quiet on set; dependable; dry wit in press junkets.",
        performance_style="Economy and weight; stillness sells rank.",
        voice_notes="Low steady baritone; Yorkshire slips when tired.",
        personality="Dependable over charismatic; humor bone-dry.",
        signature_looks="Charcoal suits, stubble, practical watch.",
        casting_notes="Period military, crime; stubble continuity.",
        wardrobe_color="charcoal",
        dob="November 20, 1987",
    ),
    _a(
        stage_name="Pierre Dubois",
        gender="male",
        world_region="europe_west",
        age=41,
        ethnicity="French",
        nationality="France",
        heritage="Lyon and Paris roots",
        languages=["French (native)", "English (fluent)"],
        physical=(
            "5'11\", slim elegant build, salt-and-pepper hair swept back, dark brown eyes, "
            "olive skin, neat goatee."
        ),
        archetypes=["Sophisticated antagonist", "Chef / artist lead", "Mocking intellect"],
        moods=["sophisticated", "mocking", "charismatic"],
        on_screen_mood="Sophisticated charm; mocking edge when winning.",
        off_screen_mood="Charismatic interviews; playful mockery with friends on video.",
        performance_style="Precision and flair; hands choreographed.",
        voice_notes="Melodic French baritone; English crisp.",
        personality="Pride in craft; mockery rarely cruel.",
        signature_looks="Tailored navy, silk scarf, goatee trimmed.",
        casting_notes="Drama, culinary; goatee locked.",
        wardrobe_color="navy",
        dob="April 14, 1985",
    ),
    _a(
        stage_name="Lars Eriksson",
        gender="male",
        world_region="europe_west",
        age=34,
        ethnicity="Swedish",
        nationality="Sweden",
        heritage="Gothenburg shipyard family",
        languages=["Swedish (native)", "English (fluent)"],
        physical=(
            "6'2\", broad Viking-lean build, short blonde hair, ice-blue eyes, fair skin, "
            "square jaw, forearm scar."
        ),
        archetypes=["Strong silent lead", "Rescue worker", "Loyal brother"],
        moods=["laconic", "dependable", "gentle"],
        on_screen_mood="Laconic; gentleness in small acts.",
        off_screen_mood="Few words off-camera; dependable, gentle with kids on set.",
        performance_style="Physical presence; emotion in jaw.",
        voice_notes="Low sparse delivery; Swedish accent faint.",
        personality="Shows care through action.",
        signature_looks="Work boots, plain tees, flannel.",
        casting_notes="Action, family drama; scar continuity.",
        wardrobe_color="grey",
        dob="October 9, 1991",
    ),
    _a(
        stage_name="Marco Esposito",
        gender="male",
        world_region="europe_west",
        age=36,
        ethnicity="Italian",
        nationality="Italy",
        heritage="Naples and Milan roots",
        languages=["Italian (native)", "English (conversational)"],
        physical=(
            "5'10\", compact muscular build, thick dark curls, warm brown eyes, olive skin, "
            "expressive hands, five-o'clock shadow."
        ),
        archetypes=["Passionate romantic lead", "Hot-headed brother", "Theatrical artist"],
        moods=["passionate", "theatrical", "loyal"],
        on_screen_mood="Passion always on offer; theatrical when hurt.",
        off_screen_mood="Big hugs; sings on set; theatrical in video interviews.",
        performance_style="Full-body emotion; voice carries.",
        voice_notes="Rich tenor; Italian peaks on anger.",
        personality="Loyalty and jealousy intertwined.",
        signature_looks="Open collar, gold chain, curls.",
        casting_notes="Romance, family; curls locked.",
        wardrobe_color="white",
        dob="June 2, 1990",
    ),
    _a(
        stage_name="Finn MacAllister",
        gender="male",
        world_region="europe_west",
        age=33,
        ethnicity="Scottish",
        nationality="United Kingdom",
        heritage="Highland and Glasgow roots",
        languages=["English (Scottish accent)", "Scottish Gaelic (basic)"],
        physical=(
            "6'0\", rugged athletic build, auburn beard and short hair, green eyes, "
            "fair weathered skin, tattoo sleeve left arm."
        ),
        archetypes=["Outlander energy lead", "Gruff protector", "Secret softie"],
        moods=["gruff", "protective", "wry"],
        on_screen_mood="Gruff exterior; wry softness for loved ones.",
        off_screen_mood="Gruff banter; secretly soft with animals on BTS video.",
        performance_style="Physical honesty; humor through beard.",
        voice_notes="Rumbling Scottish baritone.",
        personality="Protector identity; softness hidden.",
        signature_looks="Kilt formal canon, beard, sleeve visible.",
        casting_notes="Period, action; tattoo sleeve continuity.",
        tattoos="Left arm Celtic knot sleeve — always visible in short sleeves.",
        wardrobe_color="black",
        dob="January 25, 1993",
    ),
    _a(
        stage_name="Dmitri Kozlov",
        gender="male",
        world_region="europe_east",
        age=40,
        ethnicity="Russian",
        nationality="Russia",
        heritage="Moscow; former ballet academy",
        languages=["Russian (native)", "English (fluent)"],
        physical=(
            "6'1\", lean powerful build, shaved head, pale grey eyes, fair skin, "
            "sharp cheekbones, straight posture."
        ),
        archetypes=["Brooding lead", "Assassin poise", "Redemption arc"],
        moods=["brooding", "precise", "intense"],
        on_screen_mood="Brooding stillness; intensity in still hands.",
        off_screen_mood="Intense focus; rare smile in behind-the-scenes footage.",
        performance_style="Ballet economy; violence clean.",
        voice_notes="Low Russian baritone; quiet threat.",
        personality="Redemption sought in silence.",
        signature_looks="Black turtleneck, shaved head, no jewelry.",
        casting_notes="Thriller, action; head shaved locked.",
        wardrobe_color="black",
        dob="December 5, 1985",
    ),
    _a(
        stage_name="Tomas Novak",
        gender="male",
        world_region="europe_east",
        age=26,
        ethnicity="Czech",
        nationality="Czech Republic",
        heritage="Prague arts district",
        languages=["Czech (native)", "English (fluent)"],
        physical=(
            "5'11\", lanky build, messy brown hair, hazel eyes, pale skin, "
            "angular features, wire-frame glasses off-duty."
        ),
        archetypes=["Quirky indie lead", "Coder sidekick", "Earnest romantic"],
        moods=["quirky", "earnest", "anxious"],
        on_screen_mood="Quirky deflection; earnest when honest.",
        off_screen_mood="Awkward-charming in video interviews; earnest with fans.",
        performance_style="Naturalistic fidget; honesty in pause.",
        voice_notes="Soft tenor; rapid Czech-English code-switch.",
        personality="Anxiety as fuel for honesty.",
        signature_looks="Hoodies, glasses, muted tones.",
        casting_notes="Indie, tech comedy; glasses optional per scene.",
        wardrobe_color="grey",
        dob="May 17, 1999",
    ),
    _a(
        stage_name="Viktor Petrov",
        gender="male",
        world_region="europe_east",
        age=35,
        ethnicity="Ukrainian-Canadian",
        nationality="Canada",
        heritage="Kyiv and Toronto roots",
        languages=["Ukrainian (fluent)", "English (native)", "Russian (conversational)"],
        physical=(
            "6'0\", solid build, short dark blond hair, blue-grey eyes, fair skin, "
            "square jaw, small chin scar."
        ),
        archetypes=["Immigrant saga lead", "Construction boss", "Guarded father"],
        moods=["guarded", "dry", "resilient"],
        on_screen_mood="Guarded speech; dry wit unexpected.",
        off_screen_mood="Guarded press; dry humor with crew; resilient in documentaries.",
        performance_style="Weight in shoulders; love in labor.",
        voice_notes="Low calm voice; Ukrainian lullaby cadence.",
        personality="Resilience without speechifying.",
        signature_looks="Work shirt, scar, wedding ring prop.",
        casting_notes="Family drama; scar and ring continuity.",
        wardrobe_color="navy",
        dob="August 24, 1990",
    ),
    _a(
        stage_name="Marcus Cole",
        gender="male",
        world_region="north_america",
        age=32,
        ethnicity="African American",
        nationality="United States",
        heritage="Atlanta and Chicago family roots",
        languages=["English (native)"],
        physical=(
            "6'2\", athletic muscular build, close-cropped black hair, deep brown eyes, "
            "rich brown skin, easy smile."
        ),
        archetypes=["Romantic lead", "Athlete past", "Charming mediator"],
        moods=["charming", "easygoing", "steadfast"],
        on_screen_mood="Charming default; steadfast when stakes rise.",
        off_screen_mood="Easygoing king of set; charming in talk-show video formats.",
        performance_style="Relaxed charm; athletic movement background.",
        voice_notes="Warm baritone; laugh contagious.",
        personality="Mediator; avoids conflict until loyalty demands.",
        signature_looks="Clean casual, fitted tees, confident posture.",
        casting_notes="Rom-com, sports drama; smile signature.",
        wardrobe_color="cobalt blue",
        dob="July 4, 1993",
    ),
    _a(
        stage_name="Connor Mitchell",
        gender="male",
        world_region="north_america",
        age=29,
        ethnicity="Irish-American",
        nationality="United States",
        heritage="Boston Irish family",
        languages=["English (native, Boston)"],
        physical=(
            "5'11\", lean scrappy build, messy dark red hair, blue eyes, fair freckled skin, "
            "permanent smirk potential."
        ),
        archetypes=["Roguish lead", "Underdog lawyer", "Loyal troublemaker"],
        moods=["roguish", "loyal", "quick"],
        on_screen_mood="Roguish charm; loyalty in action.",
        off_screen_mood="Bar-story energy in interviews; loyal to ensemble.",
        performance_style="Fast talk; heart under swagger.",
        voice_notes="Boston clip; softens for sincerity.",
        personality="Trouble finds him; loyalty keeps him.",
        signature_looks="Leather jacket, scuffed boots, smirk.",
        casting_notes="Legal, crime, rom-com.",
        wardrobe_color="black",
        dob="March 17, 1997",
    ),
    _a(
        stage_name="Elijah Brooks",
        gender="male",
        world_region="north_america",
        age=37,
        ethnicity="African American",
        nationality="United States",
        heritage="Detroit and Harlem roots",
        languages=["English (native)"],
        physical=(
            "6'3\", imposing lean build, bald head, deep brown eyes, dark brown skin, "
            "neat beard, silver ear stud."
        ),
        archetypes=["Protector lead", "Intense father", "Quiet authority"],
        moods=["intense", "protective", "measured"],
        on_screen_mood="Intensity restrained; protection through presence.",
        off_screen_mood="Measured interviews; protective of younger cast on video.",
        performance_style="Stillness fills frame; voice low.",
        voice_notes="Deep measured baritone.",
        personality="Protection as love language.",
        signature_looks="Bald, beard, tailored dark layers.",
        casting_notes="Drama, crime; bald locked.",
        wardrobe_color="black",
        dob="February 2, 1988",
    ),
    _a(
        stage_name="Kenji Sato",
        gender="male",
        world_region="east_asia",
        age=34,
        ethnicity="Japanese",
        nationality="Japan",
        heritage="Tokyo and Hokkaido roots",
        languages=["Japanese (native)", "English (fluent)"],
        physical=(
            "5'10\", lean martial-arts build, black hair medium length swept back, "
            "dark brown eyes, fair skin, calm face."
        ),
        archetypes=["Samurai-modern lead", "Disciplined partner", "Subtle humor"],
        moods=["disciplined", "subtle", "honorable"],
        on_screen_mood="Discipline visible; subtle humor in blink.",
        off_screen_mood="Formal polite; subtle deadpan humor in BTS.",
        performance_style="Economy; honor in posture.",
        voice_notes="Calm baritone; Japanese formality levels.",
        personality="Honor before self-expression.",
        signature_looks="Minimal wardrobe, clean lines, swept hair.",
        casting_notes="Action, period-modern fusion.",
        wardrobe_color="black",
        dob="September 9, 1991",
    ),
    _a(
        stage_name="Wei Zhang",
        gender="male",
        world_region="east_asia",
        age=31,
        ethnicity="Chinese-American",
        nationality="United States",
        heritage="Shanghai and San Francisco roots",
        languages=["Mandarin (fluent)", "English (native)"],
        physical=(
            "5'11\", slim tech-founder build, short neat black hair, sharp dark eyes, "
            "light beige skin, thin-frame glasses."
        ),
        archetypes=["Strategist lead", "Startup thriller", "Reserved romantic"],
        moods=["strategic", "reserved", "witty"],
        on_screen_mood="Strategic calm; witty when comfortable.",
        off_screen_mood="Reserved press; witty in podcast video long-form.",
        performance_style="Brain visible in eyes; still hands.",
        voice_notes="Clear Mandarin-English; pace quick when excited.",
        personality="Plans three moves ahead; warmth private.",
        signature_looks="Tech casual, glasses, neutral palette.",
        casting_notes="Thriller, romance; glasses continuity.",
        wardrobe_color="grey",
        dob="October 1, 1994",
    ),
    _a(
        stage_name="Theo Nakamura",
        gender="male",
        world_region="east_asia",
        age=25,
        ethnicity="Japanese-American",
        nationality="United States",
        heritage="Los Angeles and Osaka roots",
        languages=["English (native)", "Japanese (fluent)"],
        physical=(
            "5'9\", skateboarder lean build, bleached-streak black hair, brown eyes, "
            "light olive skin, small ear hoop."
        ),
        archetypes=["Skater rom-com lead", "Cool outsider", "Unexpected funny"],
        moods=["cool", "playful", "sarcastic"],
        on_screen_mood="Cool slouch; sarcasm as affection.",
        off_screen_mood="Playful in skate BTS video; sarcastic with press.",
        performance_style="Loose body; comic timing in shrug.",
        voice_notes="LA casual; Japanese with grandparents.",
        personality="Cool as costume; playful core.",
        signature_looks="Oversized tees, hoop, bleached streak.",
        casting_notes="Youth rom-com; hair streak locked.",
        wardrobe_color="white",
        dob="April 20, 2001",
    ),
    _a(
        stage_name="Arjun Mehta",
        gender="male",
        world_region="south_asia",
        age=30,
        ethnicity="Indian",
        nationality="India",
        heritage="Mumbai and Bangalore roots",
        languages=["Hindi (native)", "English (fluent)", "Marathi (conversational)"],
        physical=(
            "5'10\", fit build, thick black wavy hair, warm brown eyes, medium brown skin, "
            "neat trimmed beard."
        ),
        archetypes=["Bollywood-adjacent lead", "Thoughtful engineer", "Witty romantic"],
        moods=["thoughtful", "witty", "romantic"],
        on_screen_mood="Thoughtful pause; witty release.",
        off_screen_mood="Thoughtful interviews; witty on panel shows.",
        performance_style="Musical rhythm optional; dance capable.",
        voice_notes="Warm baritone; Hindi poetry cadence.",
        personality="Romantic idealist with engineer brain.",
        signature_looks="Kurta formal, beard trimmed, warm eyes.",
        casting_notes="Romance, tech; beard continuity.",
        wardrobe_color="navy",
        dob="January 14, 1996",
    ),
    _a(
        stage_name="Ravi Menon",
        gender="male",
        world_region="south_asia",
        age=38,
        ethnicity="British Sri Lankan",
        nationality="United Kingdom",
        heritage="Colombo and London roots",
        languages=["English (native)", "Tamil (fluent)", "Sinhala (conversational)"],
        physical=(
            "5'9\", soft build, salt-pepper hair, gentle brown eyes, medium brown skin, "
            "reading glasses, kind lines."
        ),
        archetypes=["Gentle mentor", "Teacher lead", "Observant father"],
        moods=["gentle", "observant", "patient"],
        on_screen_mood="Gentle authority; patience under provocation.",
        off_screen_mood="Patient with students on set; observant documentary narrator.",
        performance_style="Listen-first acting; kindness without softness.",
        voice_notes="Soft British; Tamil lullaby rhythm.",
        personality="Patience is discipline.",
        signature_looks="Cardigan canon, glasses, warm tones.",
        casting_notes="Family, education drama.",
        wardrobe_color="burgundy",
        dob="November 30, 1987",
    ),
    _a(
        stage_name="Oluwaseun Bakare",
        gender="male",
        world_region="sub_saharan_africa",
        age=33,
        ethnicity="Nigerian",
        nationality="Nigeria",
        heritage="Lagos Yoruba family",
        languages=["English (fluent)", "Yoruba (native)"],
        physical=(
            "6'0\", broad charismatic build, short fade haircut, deep brown eyes, "
            "rich dark brown skin, perfect teeth smile."
        ),
        archetypes=["Political drama lead", "Persuasive orator", "Charm offensive"],
        moods=["confident", "persuasive", "magnetic"],
        on_screen_mood="Persuasion as performance; magnetism in stillness.",
        off_screen_mood="Magnetic speaker in video; confident with press.",
        performance_style="Oratory training visible; smile weaponized.",
        voice_notes="Rich baritone; orator pace.",
        personality="Charm in service of cause.",
        signature_looks="Sharp suits, fade, smile.",
        casting_notes="Political, legal drama.",
        wardrobe_color="white",
        dob="June 12, 1992",
    ),
    _a(
        stage_name="Malik Diallo",
        gender="male",
        world_region="sub_saharan_africa",
        age=29,
        ethnicity="Senegalese-French",
        nationality="France",
        heritage="Dakar and Paris roots",
        languages=["French (native)", "Wolof (fluent)", "English (fluent)"],
        physical=(
            "6'1\", model-lean build, close natural hair, deep brown eyes, "
            "deep ebony skin, high cheekbones."
        ),
        archetypes=["Fashion lead", "Provocative artist", "Elegant rebel"],
        moods=["elegant", "provocative", "cool"],
        on_screen_mood="Elegant provocation; cool under flashbulbs.",
        off_screen_mood="Cool fashion video presence; provocative in art interviews.",
        performance_style="Body as instrument; still face.",
        voice_notes="French lyric baritone.",
        personality="Art before approval.",
        signature_looks="Avant-garde layers, natural hair.",
        casting_notes="Fashion, drama; cheekbones light-critical.",
        wardrobe_color="black",
        dob="May 25, 1996",
    ),
    _a(
        stage_name="Diego Morales",
        gender="male",
        world_region="latin_america",
        age=28,
        ethnicity="Mexican",
        nationality="Mexico",
        heritage="Mexico City and Oaxaca roots",
        languages=["Spanish (native)", "English (conversational)"],
        physical=(
            "5'11\", wiry muscular build, black wavy hair, intense dark eyes, "
            "bronze skin, stubble, silver chain."
        ),
        archetypes=["Hot-headed lead", "Musician past", "Charismatic rebel"],
        moods=["charismatic", "hot-tempered", "soulful"],
        on_screen_mood="Charisma first; temper flash then regret.",
        off_screen_mood="Soulful musician in video sessions; charismatic interviews.",
        performance_style="Music in movement; temper in jaw.",
        voice_notes="Gravelly tenor; Spanish song phrasing.",
        personality="Soul over strategy.",
        signature_looks="Denim, chain, stubble.",
        casting_notes="Music drama, romance.",
        wardrobe_color="black",
        dob="October 12, 1997",
    ),
    _a(
        stage_name="Rafael Costa",
        gender="male",
        world_region="latin_america",
        age=35,
        ethnicity="Brazilian",
        nationality="Brazil",
        heritage="Rio and São Paulo roots",
        languages=["Portuguese (native)", "English (fluent)", "Spanish (conversational)"],
        physical=(
            "6'0\", soccer-athlete build, curly dark brown hair, warm hazel eyes, "
            "sun-bronze skin, easy grin."
        ),
        archetypes=["Romantic lead", "Flirtatious neighbor", "Soulful athlete"],
        moods=["flirtatious", "soulful", "warm"],
        on_screen_mood="Flirt as language; soulful when alone.",
        off_screen_mood="Warm flirt in variety shows; soulful acoustic video side.",
        performance_style="Physical grace; smile as punctuation.",
        voice_notes="Warm Portuguese-tinged English.",
        personality="Warmth default; soulful in loss.",
        signature_looks="Linens, open shirts, curls.",
        casting_notes="Romance, sports; curls locked.",
        wardrobe_color="cobalt blue",
        dob="July 9, 1990",
    ),
    _a(
        stage_name="Carlos Mendez",
        gender="male",
        world_region="latin_america",
        age=42,
        ethnicity="Argentinian",
        nationality="Argentina",
        heritage="Buenos Aires tango district",
        languages=["Spanish (native)", "English (fluent)"],
        physical=(
            "5'10\", lean dancer build, slicked-back grey at temples black hair, "
            "sad dark eyes, olive skin, thin mustache."
        ),
        archetypes=["Melancholic lead", "Tango past", "Magnetic aging romantic"],
        moods=["melancholic", "magnetic", "proud"],
        on_screen_mood="Melancholy in stillness; magnetism in dance.",
        off_screen_mood="Melancholic interviews; magnetic in dance video clips.",
        performance_style="Tango posture always; pride in spine.",
        voice_notes="Low Spanish baritone; tango phrasing.",
        personality="Pride masks longing.",
        signature_looks="Black shirt, mustache, dance shoes.",
        casting_notes="Romance, period; mustache locked.",
        wardrobe_color="black",
        dob="April 23, 1983",
    ),
    _a(
        stage_name="Amir Khalil",
        gender="male",
        world_region="middle_east_north_africa",
        age=32,
        ethnicity="Egyptian-American",
        nationality="United States",
        heritage="Cairo and New Jersey roots",
        languages=["Arabic (fluent)", "English (native)"],
        physical=(
            "6'0\", athletic build, short dark curly hair, amber-brown eyes, olive skin, "
            "trim beard, warm smile."
        ),
        archetypes=["Principled lead", "Doctor past", "Smooth diplomat"],
        moods=["smooth", "principled", "charming"],
        on_screen_mood="Smooth diplomacy; principle when tested.",
        off_screen_mood="Charming talk-show; principled in charity video.",
        performance_style="Calm hands; charm evidence-based.",
        voice_notes="Smooth baritone; Arabic prayer cadence.",
        personality="Principle without preachiness.",
        signature_looks="Scrubs canon, beard trimmed, warm smile.",
        casting_notes="Medical, political drama.",
        wardrobe_color="navy",
        dob="August 11, 1993",
    ),
    _a(
        stage_name="Hassan Odeh",
        gender="male",
        world_region="middle_east_north_africa",
        age=36,
        ethnicity="Jordanian-British",
        nationality="United Kingdom",
        heritage="Amman and London roots",
        languages=["Arabic (fluent)", "English (native)"],
        physical=(
            "5'11\", solid build, short black hair, calm dark eyes, olive skin, "
            "neat beard, still posture."
        ),
        archetypes=["Calm strategist", "Spy drama", "Razor-sharp counsel"],
        moods=["calm", "sharp", "watchful"],
        on_screen_mood="Calm surface; razor lines when speaking.",
        off_screen_mood="Watchful quiet; sharp in long-form interview video.",
        performance_style="Stillness; words measured.",
        voice_notes="Low calm baritone; Arabic precision.",
        personality="Watchful before acting.",
        signature_looks="Tailored grey, beard neat.",
        casting_notes="Thriller, legal.",
        wardrobe_color="grey",
        dob="December 18, 1989",
    ),
    _a(
        stage_name="Sam Brody",
        gender="male",
        world_region="oceania_pacific",
        age=27,
        ethnicity="Australian",
        nationality="Australia",
        heritage="Melbourne urban; surf coast weekends",
        languages=["English (native Australian)"],
        physical=(
            "6'1\", surfer lean build, sun-bleached brown hair, hazel eyes, tan skin, "
            "relaxed grin, scar on chin."
        ),
        archetypes=["Golden-retriever lead", "Surf comedy", "Irreverent hero"],
        moods=["irreverent", "loyal", "easy"],
        on_screen_mood="Irreverent humor; loyal when stakes land.",
        off_screen_mood="Golden-retriever BTS energy; irreverent podcast video.",
        performance_style="Loose physical comedy; loyal eyes.",
        voice_notes="Australian drawl; laugh frequent.",
        personality="Loyalty through jokes.",
        signature_looks="Board shorts, chin scar, tan.",
        casting_notes="Comedy, surf; scar continuity.",
        wardrobe_color="cobalt blue",
        dob="February 6, 1999",
    ),
    _a(
        stage_name="Jayden Tau",
        gender="male",
        world_region="oceania_pacific",
        age=24,
        ethnicity="Māori-New Zealander",
        nationality="New Zealand",
        heritage="Ngāpuhi iwi; Auckland raised",
        languages=["English (native)", "Te Reo Māori (fluent)"],
        physical=(
            "5'11\", powerful rugby build, short dark hair with traditional line-up, "
            "brown eyes, brown skin, bone carving necklace."
        ),
        archetypes=["Grounded warrior lead", "Community anchor", "Playful giant"],
        moods=["grounded", "playful", "proud"],
        on_screen_mood="Grounded strength; playful with trusted crew.",
        off_screen_mood="Playful haka-adjacent energy in video; proud cultural advocate.",
        performance_style="Physical power with gentle hands.",
        voice_notes="Deep warm baritone; Te Reo ceremonial cadence.",
        personality="Pride in culture; playfulness in safe spaces.",
        signature_looks="Bone necklace, line-up hair, traditional formal canon.",
        casting_notes="Action, community drama; necklace continuity.",
        wardrobe_color="black",
        dob="June 21, 2001",
    ),
]

assert len(ROSTER_50) == 50
assert sum(1 for a in ROSTER_50 if a.gender == "female") == 25
assert sum(1 for a in ROSTER_50 if a.gender == "male") == 25