"""Ten additional female roster actors — editorial-beauty emphasis, striking features."""

from __future__ import annotations

from roster_50_data import _a
from actor_profile_generator import ActorProfile

ROSTER_STUNNING_10: list[ActorProfile] = [
    _a(
        stage_name="Sienna Laurent",
        gender="female",
        world_region="europe_west",
        age=28,
        ethnicity="French",
        nationality="France",
        heritage="Provence and Paris couture circles",
        languages=["French (native)", "English (fluent)", "Italian (conversational)"],
        physical=(
            "5'10\", runway-lean build, razor-sharp cheekbones, feline emerald-green eyes, "
            "full chestnut waves to mid-back, luminous porcelain-olive skin, sculpted jaw."
        ),
        archetypes=["High-fashion lead", "Femme fatale with intellect", "Editorial drama icon"],
        moods=["magnetic", "cool", "precise"],
        on_screen_mood="Magnetic stillness; heat delivered through a half-smile and held gaze.",
        off_screen_mood="Polished and observant in interviews; dry wit when comfortable.",
        performance_style="Economical gestures; camera finds her in negative space.",
        voice_notes="Low melodic French cadence; English crisp when strategic.",
        personality="Perfectionist poise; loyalty shown through fierce preparation.",
        signature_looks="Sleek center-part waves, berry lip, black-and-gold evening wear.",
        casting_notes="Beauty/editorial leads; cheekbone and eye line are continuity anchors.",
        wardrobe_color="deep burgundy",
        dob="April 14, 1998",
        full_legal_name="Sienna Marie Laurent",
    ),
    _a(
        stage_name="Katya Morozova",
        gender="female",
        world_region="europe_east",
        age=24,
        ethnicity="Ukrainian",
        nationality="Ukraine",
        heritage="Kyiv and Odesa artistic family",
        languages=["Ukrainian (native)", "Russian (fluent)", "English (fluent)"],
        physical=(
            "5'9\", statuesque model proportions, ice-blue almond eyes, platinum-blonde straight hair "
            "to waist, angular cheekbones, pale luminous skin, striking arched brows."
        ),
        archetypes=["Ice queen lead", "Ballet-trained survivor", "Cover-model turned actor"],
        moods=["glacial", "defiant", "sensual"],
        on_screen_mood="Glacial control until a single crack reveals devastation.",
        off_screen_mood="Guarded with press; warm and teasing with dance-trained crew.",
        performance_style="Physical discipline; emotion lives in posture and breath.",
        voice_notes="Cool low register; softens in intimate dialogue.",
        personality="Survivor's discipline; tenderness reserved for earned trust.",
        signature_looks="Slick low bun, nude lip, ice-palette wardrobe, bare collarbone.",
        casting_notes="Editorial fantasy, period drama; bone structure reads in wide shots.",
        wardrobe_color="ice blue",
        dob="January 29, 2002",
        full_legal_name="Kateryna Oleksandrivna Morozova",
    ),
    _a(
        stage_name="Serena Blake",
        gender="female",
        world_region="north_america",
        age=30,
        ethnicity="African American",
        nationality="United States",
        heritage="Atlanta and Charleston Gullah-Geechee coastal line",
        languages=["English (native, Southern coastal)"],
        physical=(
            "5'8\", toned hourglass build, breathtaking high cheekbones, luminous deep brown skin, "
            "full sculpted lips, large almond dark eyes with gold flecks, glossy black coiled curls."
        ),
        archetypes=["Power-lead beauty", "Romantic drama queen", "Executive glam"],
        moods=["radiant", "commanding", "warm"],
        on_screen_mood="Radiant confidence; command arrives as a quiet chin lift.",
        off_screen_mood="Effusive warmth on set; candid laughter in behind-the-scenes.",
        performance_style="Open emotional register; owns two-shots with stillness.",
        voice_notes="Rich Southern coastal timbre; can sharpen to boardroom steel.",
        personality="Generous charisma; boundaries firm when disrespected.",
        signature_looks="Bronze glow makeup, gold hoops, emerald silk, defined curls.",
        casting_notes="Lead romance and prestige TV; skin and cheekbone continuity critical.",
        wardrobe_color="emerald green",
        dob="June 3, 1996",
        full_legal_name="Serena Alexandria Blake",
    ),
    _a(
        stage_name="Camille Reyes",
        gender="female",
        world_region="latin_america",
        age=26,
        ethnicity="Colombian",
        nationality="Colombia",
        heritage="Cartagena coastal and Bogotá upland mix",
        languages=["Spanish (native)", "English (fluent)"],
        physical=(
            "5'7\", curvy athletic build, dramatic dark espresso eyes, thick glossy raven hair "
            "past shoulders, honey-golden skin, striking cupid's bow, defined cheek hollows."
        ),
        archetypes=["Passion-lead", "Dance-driven seductress", "Revenge glam"],
        moods=["fiery", "playful", "smoldering"],
        on_screen_mood="Playful spark that flips to smolder without warning.",
        off_screen_mood="High energy on set; affectionate with collaborators.",
        performance_style="Hip-and-shoulder storytelling; eyes lead every beat.",
        voice_notes="Warm Colombian lilt; English bright with musical rhythm.",
        personality="Passion-forward; forgives slowly, loves fiercely.",
        signature_looks="Wet-look waves, coral lip, gold body chain, tropical noir palette.",
        casting_notes="Romance thriller, music-driven drama; eye and lip shape lock continuity.",
        wardrobe_color="coral",
        dob="September 21, 1999",
        full_legal_name="Camille Andrea Reyes Vargas",
    ),
    _a(
        stage_name="Noor El-Amir",
        gender="female",
        world_region="middle_east_north_africa",
        age=27,
        ethnicity="Lebanese",
        nationality="Lebanon",
        heritage="Beirut old-city merchant and atelier family",
        languages=["Arabic (native, Levantine)", "French (fluent)", "English (fluent)"],
        physical=(
            "5'6\", elegant slim build, captivating hazel-green eyes with thick lashes, "
            "aristocratic straight nose, olive luminous skin, waist-length dark chestnut waves."
        ),
        archetypes=["Mediterranean muse", "Political drama beauty", "Old-money mystery"],
        moods=["enigmatic", "graceful", "sharp"],
        on_screen_mood="Enigmatic grace; precision in the pause before answering.",
        off_screen_mood="Gracious with press; fiercely private off-camera.",
        performance_style="Regal micro-expressions; stillness as power.",
        voice_notes="Melodic Levantine Arabic; French purr in English scenes.",
        personality="Old-soul composure; wit sharp when cornered.",
        signature_looks="Soft smoky eye, nude rose lip, cream silk, loose waves.",
        casting_notes="Prestige international drama; eye color and nose profile are anchors.",
        wardrobe_color="champagne gold",
        dob="March 8, 1999",
        full_legal_name="Noor Yasmin El-Amir",
    ),
    _a(
        stage_name="Amahle Ndaba",
        gender="female",
        world_region="sub_saharan_africa",
        age=25,
        ethnicity="Zulu South African",
        nationality="South Africa",
        heritage="KwaZulu-Natal royal craft lineage (ceremonial, not political claim)",
        languages=["Zulu (native)", "English (fluent)", "Xhosa (conversational)"],
        physical=(
            "5'9\", tall regal build, breathtaking sculpted cheekbones, almond deep brown eyes, "
            "rich ebony skin with natural glow, full lips, shaved-side natural black afro crown."
        ),
        archetypes=["Regal lead", "Epic romance heroine", "Warrior-poet beauty"],
        moods=["regal", "fierce", "tender"],
        on_screen_mood="Regal bearing; tenderness appears as lowered gaze.",
        off_screen_mood="Poised in interviews; joyful dancer off set.",
        performance_style="Grounded physical presence; grief in the shoulders.",
        voice_notes="Resonant low alto; Zulu song cadence in emotional peaks.",
        personality="Pride in heritage; gentle with children and animals on set.",
        signature_looks="Bronze highlight, copper lip, white linen, sculptural afro silhouette.",
        casting_notes="Epic and romance leads; profile and cheekbone read in turnaround sheets.",
        wardrobe_color="copper bronze",
        dob="November 17, 2000",
        full_legal_name="Amahle Nokuthula Ndaba",
    ),
    _a(
        stage_name="Ji-Yeon Park",
        gender="female",
        world_region="east_asia",
        age=23,
        ethnicity="Korean",
        nationality="South Korea",
        heritage="Seoul Gangnam and Busan film-family roots",
        languages=["Korean (native)", "English (fluent)"],
        physical=(
            "5'6\", slim dancer build, glass-skin luminous complexion, sharp V-line jaw, "
            "striking dark monolid eyes with soft gradient, sleek black hair with airy bangs."
        ),
        archetypes=["K-drama lead beauty", "Idol-to-actor crossover", "Melancholy romantic"],
        moods=["ethereal", "wistful", "determined"],
        on_screen_mood="Ethereal surface; determination in tightened jaw.",
        off_screen_mood="Sweet with fans; focused note-taker on set.",
        performance_style="Reactive listening; tears without melodrama.",
        voice_notes="Soft Seoul standard; English gentle and clear.",
        personality="Disciplined trainee mindset; vulnerability earned on screen.",
        signature_looks="Dewy skin, gradient lip, pastel knits, see-through bangs.",
        casting_notes="Romance and youth prestige; jawline and skin finish lock continuity.",
        wardrobe_color="lavender",
        dob="February 2, 2003",
        full_legal_name="Park Ji-Yeon",
    ),
    _a(
        stage_name="Ananya Reddy",
        gender="female",
        world_region="south_asia",
        age=29,
        ethnicity="Indian (Telugu)",
        nationality="India",
        heritage="Hyderabad Deccan and Chennai cinema family",
        languages=["Telugu (native)", "Hindi (fluent)", "English (fluent)"],
        physical=(
            "5'5\", graceful curvy build, striking large expressive dark eyes, thick glossy "
            "black hair to hips, warm copper-toned skin, defined brows, full lips, elegant nose."
        ),
        archetypes=["Bollywood prestige lead", "Classical dancer beauty", "Family saga anchor"],
        moods=["luminous", "passionate", "grounded"],
        on_screen_mood="Luminous warmth; passion arrives as focused stillness.",
        off_screen_mood="Grounded and articulate in interviews; hugs crew freely.",
        performance_style="Eyes-and-hands storytelling; dance training in posture.",
        voice_notes="Musical Telugu cadence; English polished BBC-Indian neutral.",
        personality="Family-devoted; artistic integrity non-negotiable.",
        signature_looks="Kohl-rimmed eyes, maroon lip, silk saree canon, jasmine hair.",
        casting_notes="Prestige romance and period; eye size and hair length are continuity keys.",
        wardrobe_color="maroon",
        dob="October 30, 1996",
        full_legal_name="Ananya Priya Reddy",
    ),
    _a(
        stage_name="Inés Marchetti",
        gender="female",
        world_region="latin_america",
        age=31,
        ethnicity="Argentine-Italian",
        nationality="Argentina",
        heritage="Buenos Aires Palermo and Milan maternal line",
        languages=["Spanish (native, Rioplatense)", "Italian (fluent)", "English (fluent)"],
        physical=(
            "5'8\", long-legged model build, stunning grey-blue eyes, sun-kissed olive skin, "
            "strong Roman nose, glossy dark auburn hair in loose Hollywood waves, full mouth."
        ),
        archetypes=["Tango-noir lead", "Mature seductress", "Fashion-week crossover"],
        moods=["smoldering", "witty", "proud"],
        on_screen_mood="Smoldering default; wit flashes in sideways glance.",
        off_screen_mood="Witty and physical on set; tactile director collaborator.",
        performance_style="Tango-trained hips; dialogue as duel.",
        voice_notes="Rioplatense Spanish purr; Italian hand gestures in English.",
        personality="Proud porteña energy; competitive on dance floors only.",
        signature_looks="Red lip, cat-eye liner, black slip dress, auburn waves.",
        casting_notes="Noir romance, fashion editorial; eye color and wave pattern lock.",
        wardrobe_color="ruby red",
        dob="July 19, 1994",
        full_legal_name="Inés Valentina Marchetti",
    ),
    _a(
        stage_name="Olivia Mercer",
        gender="female",
        world_region="oceania_pacific",
        age=27,
        ethnicity="Australian",
        nationality="Australia",
        heritage="Sydney beaches and Queensland reef-country roots",
        languages=["English (native, Australian)"],
        physical=(
            "5'10\", athletic surfer build, striking blue-green eyes, sun-kissed freckled skin, "
            "golden-blonde beach waves, square elegant jaw, bright white smile, toned shoulders."
        ),
        archetypes=["Coastal goddess lead", "Action-romance beauty", "Surf-noir heroine"],
        moods=["bold", "sunny", "resilient"],
        on_screen_mood="Bold sunny default; resilience in set jaw after loss.",
        off_screen_mood="Relaxed and direct in interviews; salty humor.",
        performance_style="Physical honesty; stunts sell emotional stakes.",
        voice_notes="Bright Australian coastal; can drop to gravel under stress.",
        personality="Fair-play loyalist; avoids pretense.",
        signature_looks="Salt-spray blonde, minimal makeup, turquoise bikini canon, tan lines optional per script.",
        casting_notes="Action romance and coastal drama; eye color and freckle map continuity.",
        wardrobe_color="turquoise",
        dob="December 12, 1998",
        full_legal_name="Olivia Jane Mercer",
    ),
]