"""Ten additional male roster actors — editorial-leading-man emphasis, striking features."""

from __future__ import annotations

from roster_50_data import _a
from actor_profile_generator import ActorProfile

ROSTER_STUNNING_MALES_10: list[ActorProfile] = [
    _a(
        stage_name="Luca Fontaine",
        gender="male",
        world_region="europe_west",
        age=29,
        ethnicity="French-Italian",
        nationality="France",
        heritage="Côte d'Azur and Milan fashion-family roots",
        languages=["French (native)", "Italian (fluent)", "English (fluent)"],
        physical=(
            "6'2\", sculpted athletic build, chiseled square jaw, striking amber-hazel eyes, "
            "thick dark brown hair swept back, sun-kissed olive skin, strong brow ridge."
        ),
        archetypes=["Luxury campaign lead", "Romantic thriller hero", "Couture-era leading man"],
        moods=["smoldering", "charming", "focused"],
        on_screen_mood="Smoldering restraint; charm ignites in a slow half-grin.",
        off_screen_mood="Effortless charisma in interviews; meticulous about lighting angles.",
        performance_style="Still torso, emotion in eyes; economy in dialogue.",
        voice_notes="Low warm Mediterranean baritone; English polished Parisian.",
        personality="Competitive with himself; generous with scene partners.",
        signature_looks="Open-collar linen, gold watch, designer stubble, slicked-back hair.",
        casting_notes="Editorial romance and prestige action; jaw and eye color lock continuity.",
        wardrobe_color="midnight navy",
        dob="May 11, 1997",
        full_legal_name="Luca Alessandro Fontaine",
    ),
    _a(
        stage_name="Nikolai Volsky",
        gender="male",
        world_region="europe_east",
        age=27,
        ethnicity="Russian",
        nationality="Russia",
        heritage="St. Petersburg ballet and naval family lines",
        languages=["Russian (native)", "English (fluent)"],
        physical=(
            "6'3\", statuesque broad-shouldered build, razor Slavic cheekbones, piercing steel-grey eyes, "
            "platinum-blond cropped hair, pale striking skin, aquiline nose, defined cupid's bow."
        ),
        archetypes=["Ice-king lead", "Special-ops beauty", "Cover-model antagonist"],
        moods=["glacial", "intense", "protective"],
        on_screen_mood="Glacial control; intensity arrives as unblinking focus.",
        off_screen_mood="Reserved with press; dry humor with fight choreographers.",
        performance_style="Ballet-trained posture; violence precise, never sloppy.",
        voice_notes="Deep cool baritone; English lightly accented.",
        personality="Protective instinct; rarely shows need.",
        signature_looks="Black turtleneck, cropped blond, steel watch, no smile in stills.",
        casting_notes="Action prestige and fashion editorial; cheekbone profile critical in wide shots.",
        wardrobe_color="steel grey",
        dob="February 18, 1999",
        full_legal_name="Nikolai Andrei Volsky",
    ),
    _a(
        stage_name="Julian Cross",
        gender="male",
        world_region="north_america",
        age=31,
        ethnicity="White American",
        nationality="United States",
        heritage="Virginia old-family and Los Angeles entertainment line",
        languages=["English (native, mid-Atlantic)"],
        physical=(
            "6'1\", lean Hollywood build, classic strong jaw, captivating green-hazel eyes, "
            "wavy dark brown hair, fair skin with light tan, straight nose, full lower lip."
        ),
        archetypes=["Classic leading man", "Political drama prince", "Old-money rebel"],
        moods=["confident", "witty", "brooding"],
        on_screen_mood="Confident default; brooding in stillness before a decision.",
        off_screen_mood="Witty and polished on press tours; competitive at charity golf.",
        performance_style="Leading-man eye-line; listens with jaw set.",
        voice_notes="Warm mid-Atlantic baritone; can sharpen to boardroom cut.",
        personality="Charm as tool and truth; loyalty to directors he trusts.",
        signature_looks="Navy blazer, white tee, tousled waves, clean stubble.",
        casting_notes="Studio romance and prestige TV; eye color and wave pattern are anchors.",
        wardrobe_color="forest green",
        dob="August 7, 1994",
        full_legal_name="Julian Everett Cross",
    ),
    _a(
        stage_name="Dante Reyes",
        gender="male",
        world_region="latin_america",
        age=26,
        ethnicity="Mexican",
        nationality="Mexico",
        heritage="Guadalajara charro tradition and Mexico City film family",
        languages=["Spanish (native)", "English (fluent)"],
        physical=(
            "5'11\", compact powerful build, smoldering dark espresso eyes, thick glossy black hair "
            "worn loose, bronze-golden skin, striking cheek hollows, bold arched brows, square chin."
        ),
        archetypes=["Passion-lead", "Boxer-poet hero", "Revenge romance icon"],
        moods=["fiery", "magnetic", "tender"],
        on_screen_mood="Magnetic heat; tenderness in lowered gaze after conflict.",
        off_screen_mood="High warmth on set; sings between takes.",
        performance_style="Hip-and-shoulder storytelling; eyes sell the wound.",
        voice_notes="Rich Mexican baritone; English warm with musical rhythm.",
        personality="Pride and passion; forgives slowly.",
        signature_looks="Open white shirt, silver chain, loose dark curls, sweat sheen in action.",
        casting_notes="Romance thriller and sports drama; eye and brow shape lock continuity.",
        wardrobe_color="crimson red",
        dob="October 3, 1999",
        full_legal_name="Dante Alejandro Reyes Morales",
    ),
    _a(
        stage_name="Khalid Mansour",
        gender="male",
        world_region="middle_east_north_africa",
        age=30,
        ethnicity="Egyptian",
        nationality="Egypt",
        heritage="Cairo Nile elite and Luxor heritage tourism family",
        languages=["Arabic (native, Cairene)", "English (fluent)", "French (conversational)"],
        physical=(
            "6'0\", lean statuesque build, breathtaking desert-gold eyes with thick lashes, "
            "carved Pharaonic-profile nose, olive-golden skin, short jet-black hair, sculpted lips."
        ),
        archetypes=["Desert epic hero", "International diplomat lead", "Mystery romance"],
        moods=["regal", "enigmatic", "passionate"],
        on_screen_mood="Regal calm; passion breaks through still hands.",
        off_screen_mood="Gracious with press; fiercely private off-camera.",
        performance_style="Economical gestures; power in pause.",
        voice_notes="Melodic Cairene Arabic; English smooth and low.",
        personality="Old-soul patience; humor dry when trusted.",
        signature_looks="Cream linen suit, gold signet ring, close crop, kohl optional per role.",
        casting_notes="International prestige; profile nose and eye color continuity anchors.",
        wardrobe_color="sand gold",
        dob="March 22, 1996",
        full_legal_name="Khalid Youssef Mansour",
    ),
    _a(
        stage_name="Kofi Mensah",
        gender="male",
        world_region="sub_saharan_africa",
        age=28,
        ethnicity="Ghanaian",
        nationality="Ghana",
        heritage="Accra creative class and Ashanti craft lineage",
        languages=["English (native, Ghanaian)", "Twi (fluent)", "French (conversational)"],
        physical=(
            "6'2\", athletic model build, stunning high cheekbones, deep rich brown skin with natural glow, "
            "large almond dark eyes, full lips, short tight coils, broad shoulders, elegant neck."
        ),
        archetypes=["Global campaign lead", "Romantic drama hero", "Athlete-turned-actor"],
        moods=["radiant", "grounded", "charismatic"],
        on_screen_mood="Radiant confidence; grounding in still shoulders when stakes rise.",
        off_screen_mood="Charismatic and humble in interviews; dancer off set.",
        performance_style="Physical honesty; joy and grief both full-body.",
        voice_notes="Warm Ghanaian English; laugh lines in voice when relaxed.",
        personality="Community-minded; competitive only on dance floor.",
        signature_looks="White tee, gold chain, fresh fade, bronze skin highlight.",
        casting_notes="Lead romance and prestige; cheekbone and skin finish lock in turnaround.",
        wardrobe_color="royal blue",
        dob="July 14, 1997",
        full_legal_name="Kofi Nana Mensah",
    ),
    _a(
        stage_name="Ren Hayashi",
        gender="male",
        world_region="east_asia",
        age=25,
        ethnicity="Japanese",
        nationality="Japan",
        heritage="Tokyo Shibuya fashion district and Kyoto tea-family roots",
        languages=["Japanese (native)", "English (fluent)"],
        physical=(
            "5'11\", slim model-athletic build, sharp angular jaw, striking dark monolid eyes, "
            "sleek black hair with textured fringe, porcelain-clear skin, high cheekbones, straight nose."
        ),
        archetypes=["J-drama lead beauty", "Idol-to-film crossover", "Quiet storm romantic"],
        moods=["cool", "precise", "sensitive"],
        on_screen_mood="Cool surface; sensitivity in micro-flinch.",
        off_screen_mood="Polite and focused on set; playful in fan video.",
        performance_style="Minimalist beats; eyes carry unspoken lines.",
        voice_notes="Soft Tokyo baritone; English clear and gentle.",
        personality="Discipline-first; vulnerability earned on camera.",
        signature_looks="Oversized coat, textured fringe, single silver ear cuff.",
        casting_notes="Romance and youth prestige; fringe and jawline continuity critical.",
        wardrobe_color="charcoal black",
        dob="December 9, 2000",
        full_legal_name="Hayashi Ren",
    ),
    _a(
        stage_name="Vikram Rathore",
        gender="male",
        world_region="south_asia",
        age=32,
        ethnicity="Indian (Rajasthani)",
        nationality="India",
        heritage="Jaipur royal craft lineage (ceremonial, not political claim)",
        languages=["Hindi (native)", "Rajasthani (fluent)", "English (fluent)"],
        physical=(
            "6'0\", regal athletic build, intense large dark eyes, thick wavy black hair to collar, "
            "warm bronze skin, aristocratic straight nose, strong groomed brows, sculpted beard option."
        ),
        archetypes=["Bollywood prestige lead", "Period warrior beauty", "Family saga patriarch-young"],
        moods=["commanding", "passionate", "noble"],
        on_screen_mood="Commanding stillness; passion in clenched jaw.",
        off_screen_mood="Noble courtesy in interviews; horse-riding stories on BTS.",
        performance_style="Eyes-and-beard storytelling; sword work sells emotion.",
        voice_notes="Resonant Hindi baritone; English BBC-Indian polish.",
        personality="Honor-coded; artistic integrity non-negotiable.",
        signature_looks="Embroidered sherwani canon, groomed beard, kajal optional per role.",
        casting_notes="Epic romance and period; eye intensity and hair wave lock continuity.",
        wardrobe_color="deep maroon",
        dob="January 30, 1994",
        full_legal_name="Vikram Singh Rathore",
    ),
    _a(
        stage_name="Andre Silva",
        gender="male",
        world_region="latin_america",
        age=27,
        ethnicity="Brazilian",
        nationality="Brazil",
        heritage="Rio beach football culture and São Paulo fashion roots",
        languages=["Portuguese (native)", "Spanish (fluent)", "English (fluent)"],
        physical=(
            "6'1\", soccer-toned muscular build, striking light brown eyes, sun-kissed caramel skin, "
            "wavy dark brown hair, perfect white smile, strong jaw, athletic V-taper torso."
        ),
        archetypes=["Beach romance lead", "Sports drama hero", "Campaign golden boy"],
        moods=["playful", "magnetic", "resilient"],
        on_screen_mood="Playful magnetism; resilience in set jaw after loss.",
        off_screen_mood="Effusive warmth; dances in behind-the-scenes.",
        performance_style="Physical joy; stunts sell stakes.",
        voice_notes="Bright Brazilian Portuguese; English sunny coastal.",
        personality="Team-player energy; avoids cynicism.",
        signature_looks="Board shorts off-duty, white linen, wavy hair, tan lines optional per script.",
        casting_notes="Romance and sports prestige; smile and eye color continuity anchors.",
        wardrobe_color="teal",
        dob="April 25, 1999",
        full_legal_name="André Luiz da Silva",
    ),
    _a(
        stage_name="Ethan Shaw",
        gender="male",
        world_region="oceania_pacific",
        age=29,
        ethnicity="New Zealand European-Māori",
        nationality="New Zealand",
        heritage="Auckland creative scene and Rotorua whānau roots",
        languages=["English (native, New Zealand)", "Te Reo Māori (conversational)"],
        physical=(
            "6'2\", rugged surfer-athletic build, striking blue-green eyes, sun-weathered tan skin, "
            "sandy brown wavy hair, strong square jaw, light stubble, toned forearms, straight nose."
        ),
        archetypes=["Coastal action lead", "Eco-thriller hero", "Surf-noir romantic"],
        moods=["bold", "laid-back", "steadfast"],
        on_screen_mood="Bold laid-back default; steadfast when protecting others.",
        off_screen_mood="Dry Kiwi humor; salt-spray hair in interviews.",
        performance_style="Physical authenticity; silence carries weight.",
        voice_notes="Relaxed New Zealand baritone; gravel under stress.",
        personality="Fair-play loyalist; uncomfortable with pretense.",
        signature_looks="Wetsuit tan, flannel off-duty, stubble, turquoise ocean palette.",
        casting_notes="Action romance and coastal drama; eye color and freckle map continuity.",
        wardrobe_color="ocean teal",
        dob="November 2, 1996",
        full_legal_name="Ethan Tane Shaw",
    ),
]